condense_wildcard_suffixes = true
enum_discrim_align_threshold = 40
error_on_line_overflow = true
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
match_arm_blocks = false
max_width = 120
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 40
tab_spaces = 2
trailing_semicolon = false
unstable_features = true
use_try_shorthand = true
wrap_comments = true