[workspace]
resolver = "3"
members = ["days/gift-shop","days/secret-entrance"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"
